# Databricks App Configuration
# Thomas International Unified Talent Hub

command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]

env:
  - name: DATABRICKS_MODEL_ENDPOINT
    value: "databricks-gemini-2-5-flash"
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: PYTHONDONTWRITEBYTECODE
    value: "1"
  - name: PYTHONUNBUFFERED
    value: "1"

resources:
  - name: "ask_thom_llm"
    serving_endpoint:
      name: "databricks-gemini-2-5-flash"
      permission: "CAN_QUERY"
