# Databricks App Configuration
# IFS Talent Hub - Powered by Thomas International

name: thomas-talent-hub
description: "IFS Talent Hub - Unified Talent Management powered by Thomas International psychometrics and Databricks AI"

# App entrypoint
command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]

# Environment variables
env:
  - name: DATABRICKS_MODEL_ENDPOINT
    value: "databricks-gemini-2-5-flash"
  - name: LOG_LEVEL
    value: "DEBUG"

# CRITICAL: Define resources the app needs access to
# This whitelists the serving endpoint for the app's managed identity
resources:
  - name: "ask_thom_llm"
    serving_endpoint:
      name: "databricks-gemini-2-5-flash"
      permission: "CAN_QUERY"
